### ISSUE TITLE
Help with webpush payload encryption

### ISSUE THREAD

**Issue by dbautistadecabo** [kitcambridge/ecec#35]
Hi to all!
I'm trying to use the ecec library to encrypt a webpush payload from my C program, but I find the documentation a bit obscure, so I ask you for help!
Mozilla Firefox 57 is giving me 'Error: Bad encryption'.
This is my code (I have removed error checking for summarize):
```
#include "../ecec/include/ece.h"

const char* b64_p256dh = "BAsRT....."; // from the PushManager keys.p256dh
const char* b64_auth = "R434..."; // from the PushManager keys.auth
const char* plaintext = "If the wind in my sail on the sea stays behind me, one day I'll know how far I'll go";
uint8_t p256dh[66] = { 0 }, auth[24] = { 0 };
uint8_t salt[ECE_SALT_LENGTH] = { 0 };
uint8_t rawSenderPubKey[ECE_WEBPUSH_PUBLIC_KEY_LENGTH] = { 0 };
uint8_t ciphertext[4096] = { 0 };
size_t ciphertextLen = ece_aesgcm_ciphertext_max_length(26, 6, strlen(plaintext));
char b64_ciphertext[4096*2] = { 0 };

int len_p256dh = ece_base64url_decode(b64_p256dh, strlen(b64_p256dh), ECE_BASE64URL_IGNORE_PADDING, p256dh, ECE_WEBPUSH_PUBLIC_KEY_LENGTH);
int len_auth = ece_base64url_decode(b64_auth, strlen(b64_auth), ECE_BASE64URL_IGNORE_PADDING, auth, ECE_WEBPUSH_AUTH_SECRET_LENGTH);

int res = ece_webpush_aesgcm_encrypt(p256dh, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, auth, ECE_WEBPUSH_AUTH_SECRET_LENGTH, 26, 6, (const uint8_t*)plaintext, strlen(plaintext), salt, ECE_SALT_LENGTH, rawSenderPubKey, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, ciphertext, &ciphertextLen);

size_t dhHeaderLen = 0;
size_t saltHeaderLen = 0;
ece_webpush_aesgcm_headers_from_params(salt, ECE_SALT_LENGTH, rawSenderPubKey, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, 14, NULL, &dhHeaderLen, NULL, &saltHeaderLen);
char* dhHeader = (char*)malloc(dhHeaderLen + 1);
char* saltHeader = (char*)malloc(saltHeaderLen + 1);
ece_webpush_aesgcm_headers_from_params(salt, ECE_SALT_LENGTH, rawSenderPubKey, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, 26, dhHeader, &dhHeaderLen, saltHeader, &saltHeaderLen);
dhHeader[dhHeaderLen] = '\0';
saltHeader[saltHeaderLen] = '\0';

int len_b64_ciphertext = ece_base64url_encode(ciphertext, ciphertextLen, ECE_BASE64URL_OMIT_PADDING, b64_ciphertext, sizeof(b64_ciphertext));

printf("curl -v -X POST \\\n");
printf("     -H \"Encryption: %s\" \\\n", saltHeader);
printf("     -H \"Authorization: WebPush %s\" \\\n", out);
printf("     -H \"Crypto-Key: %s; p256ecdsa=%s\" \\\n", dhHeader, vapid_pub_key);
printf("     -H \"Content-Length: %d\" \\\n", len_b64_ciphertext);
printf("     -H \"Content-Type: application/octet-stream\" \\\n");
printf("     -H \"Content-Encoding: aesgcm\" \\\n");
printf("     -H \"TTL: 0\" \\\n");
printf("     -d \"%s\" \\\n", b64_ciphertext);
printf("     \"%s\"\n", url);
```
When I execute the curl command that this program outputs, Mozilla Firefox gives me this error:
```
PushService:decryptAndNotifyApp: Error decrypting message "https://.../notificaciones/" gAAAA..... Error: Bad encryption
Stack trace:
CryptoError@resource://gre/modules/PushCrypto.jsm:60:5
decode@resource://gre/modules/PushCrypto.jsm:332:13
```
What can I be doing wrong? And also some doubts:
- In ece_webpush_aesgcm_encrypt, which values should I pass in rs and padLen?
- In ece_base64url_decode, should I use ECE_BASE64URL_IGNORE_PADDING or ECE_BASE64URL_REQUIRE_PADDING?
As you can see, I'm somewhat lost. I hope you can help me. (If this is not the right place to ask for help, please tell me).

**Comment by ghost** [comment]
Hi @dbautistadecabo! :wave: Your code looks almost right, but a few things stand out to me:

* `p256dh` only needs to be 65 bytes, not 66. You can use `ECE_WEBPUSH_PUBLIC_KEY_LENGTH` here, too, just as you use it for `rawSenderPubKey`. ecec calls this `rawRecvPubKey` instead of `p256dh`, because it's the receiver's public key. The "receiver" is always Firefox, and the "sender" is always your app.
* The auth secret is 16 bytes, not 24.
* `ece_aesgcm_ciphertext_max_length` calculates the size of the buffer you need to hold the ciphertext. `ece_base64url_encode` can also give you the size you need for the encoded output, so no need to hard-code `4096` or `4096*2`.
* However, when you POST the ciphertext, it should be binary, not Base64-encoded, so you can remove `ece_base64url_encode` completely.

Answering your questions:

* `padLen` controls how many zeros to include in each record. This makes it harder to guess the contents of the message just by looking at the length of the encrypted payload, at the cost of increasing the payload size. There's a great explanation of padding in [this article on Web Push encryption](https://developers.google.com/web/updates/2016/03/web-push-encryption#padding) and the [`web-push-php`](https://github.com/web-push-libs/web-push-php#user-content-payload-length-security-and-performance) library. Except for the PHP library, I think most libraries omit padding by default, so 0 is a safe choice.
* `rs` should be 4096. It controls how many bytes of plaintext to include in each encrypted chunk; check out the diagram in [RFC 8188](https://tools.ietf.org/html/rfc8188#section-2) if you're curious about how this works. It's mostly useful for streaming: the smaller the chunk size, the quicker you can decrypt a large payload without buffering. Since Web Push messages are so small, and typically limited to 4k or less, you can just set this to the default of 4096. (The RFC I linked to says: "Applications that don't depend on streaming, random access, or arbitrary padding can use larger records, or even a single record." [RFC 8291](https://tools.ietf.org/html/rfc8291#section-4) goes even further and says browsers can ignore `rs` entirely, and assume 4096). I should add this as a constant, like `#define ECE_WEBPUSH_DEFAULT_RS 4096`.
* In `ece_base64url_decode`, you should use `ECE_BASE64URL_IGNORE_PADDING`, since `p256dh` and `auth` don't have padding.

Here's how I'd tweak your example:

```c
#include "../ecec/include/ece.h"

uint32_t rs = 4096;
size_t padLen = 0;

const char* b64_p256dh = "BAsRT....."; // from the PushManager keys.p256dh
const char* b64_auth = "R434..."; // from the PushManager keys.auth
const char* plaintext = "If the wind in my sail on the sea stays behind me, one day I'll know how far I'll go";
uint8_t p256dh[ECE_WEBPUSH_PUBLIC_KEY_LENGTH] = { 0 };
uint8_t auth[ECE_WEBPUSH_AUTH_SECRET_LENGTH] = { 0 };
uint8_t salt[ECE_SALT_LENGTH] = { 0 };
uint8_t rawSenderPubKey[ECE_WEBPUSH_PUBLIC_KEY_LENGTH] = { 0 };

size_t ciphertextLen = ece_aesgcm_ciphertext_max_length(rs, padLen, strlen(plaintext));
uint8_t* ciphertext = (uint8_t*)malloc(ciphertextLen);

ece_base64url_decode(b64_p256dh, strlen(b64_p256dh), ECE_BASE64URL_IGNORE_PADDING, p256dh, ECE_WEBPUSH_PUBLIC_KEY_LENGTH);
ece_base64url_decode(b64_auth, strlen(b64_auth), ECE_BASE64URL_IGNORE_PADDING, auth, ECE_WEBPUSH_AUTH_SECRET_LENGTH);

int res = ece_webpush_aesgcm_encrypt(p256dh, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, auth, ECE_WEBPUSH_AUTH_SECRET_LENGTH, rs, padLen, (const uint8_t*)plaintext, strlen(plaintext), salt, ECE_SALT_LENGTH, rawSenderPubKey, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, ciphertext, &ciphertextLen);

size_t dhHeaderLen = 0;
size_t saltHeaderLen = 0;
ece_webpush_aesgcm_headers_from_params(salt, ECE_SALT_LENGTH, rawSenderPubKey, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, rs, NULL, &dhHeaderLen, NULL, &saltHeaderLen);
char* dhHeader = (char*)malloc(dhHeaderLen + 1);
char* saltHeader = (char*)malloc(saltHeaderLen + 1);
ece_webpush_aesgcm_headers_from_params(salt, ECE_SALT_LENGTH, rawSenderPubKey, ECE_WEBPUSH_PUBLIC_KEY_LENGTH, rs, dhHeader, &dhHeaderLen, saltHeader, &saltHeaderLen);
dhHeader[dhHeaderLen] = '\0';
saltHeader[saltHeaderLen] = '\0';

FILE* file = fopen("push-message.bin", "wb");
fwrite(ciphertext, sizeof(uint8_t), ciphertextLen, file);
fclose(file);

printf("curl -v -X POST \\\n");
printf("     -H \"Encryption: %s\" \\\n", saltHeader);
printf("     -H \"Authorization: WebPush %s\" \\\n", out);
printf("     -H \"Crypto-Key: %s; p256ecdsa=%s\" \\\n", dhHeader, vapid_pub_key);
printf("     -H \"Content-Length: %zu\" \\\n", ciphertextLen);
printf("     -H \"Content-Type: application/octet-stream\" \\\n");
printf("     -H \"Content-Encoding: aesgcm\" \\\n");
printf("     -H \"TTL: 0\" \\\n");
printf("     --data-binary @push-message.bin \\\n");
printf("     \"%s\"\n", url);
```

Does that help?

**Comment by ghost** [comment]
Also, please let me know how I can improve the docs! Would it help if I included your example in the readme, maybe in a separate section for "how to send Web Push messages"?

**Comment by dbautistadecabo** [comment]
Yes! With your corrections, it works like a charm!
And yes, I think that code would be very helpful as a section in the readme.
Thank you very much!

**Comment by ghost** [comment]
Awesome, glad it's working for you! 🎉 I added encryption examples to the readme.
