### ISSUE TITLE
Parse base64 encoded values with padding '=' characters cause error

### ISSUE THREAD

**Issue by commandus** [kitcambridge/ecec#37]
Some services like Google's MCS using padding, e.g.

encryption: salt=3jFrNEVgtPynKcHPmHXawA==

ece_webpush_aesgcm_headers_extract_params() return -13 error in this case.

**Comment by ghost** [comment]
Thanks, @commandus! This should be fixed in 8197205fd328b619a004e367b9627dbb389cab58, I'll merge it as soon as Travis is green.

In general, it's not a good idea for servers to send padding, since it's omitted in RFC 7515, and other implementations might reject it. But we can at least make ecec more forgiving, and working code is always better than following a spec to the letter! 😸

**Comment by commandus** [comment]
Ok, thanks!

вс, 6 мая 2018 г., 4:33 Kit Cambridge <notifications@github.com>:
